"""
Markdown Exporter for Learning Assistant.

This module provides Markdown output generation with Jinja2 templates.
"""

from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader, Template
from loguru import logger

from learning_assistant.core.exporters.base import BaseExporter


class MarkdownExporter(BaseExporter):
    """
    Markdown exporter using Jinja2 templates.

    Generates structured Markdown output from summary data.
    """

    def __init__(
        self, template_dir: Path | None = None, template_name: str = "video_summary.md"
    ) -> None:
        """
        Initialize Markdown exporter.

        Args:
            template_dir: Directory containing Markdown templates
            template_name: Name of template file to use
        """
        super().__init__(template_dir)

        self.template_name = template_name

        # Initialize Jinja2 environment
        self.env = Environment(
            loader=FileSystemLoader(str(self.template_dir)),
            autoescape=False,
            trim_blocks=True,
            lstrip_blocks=True,
        )

        logger.info(f"MarkdownExporter initialized with template: {template_name}")

    def export(
        self,
        data: dict[str, Any],
        output_path: Path,
        **kwargs: Any,
    ) -> None:
        """
        Export data to Markdown file.

        Args:
            data: Data to export (video summary)
            output_path: Output Markdown file path
            **kwargs: Additional parameters (e.g., custom template)
        """
        # Generate Markdown content
        content = self.export_to_string(data, **kwargs)

        # Ensure output directory exists
        self.ensure_output_dir(output_path)

        # Write to file
        output_path.write_text(content, encoding="utf-8")

        logger.info(f"Markdown exported to: {output_path}")

    def export_to_string(
        self,
        data: dict[str, Any],
        **kwargs: Any,
    ) -> str:
        """
        Export data to Markdown string.

        Args:
            data: Data to export
            **kwargs: Additional parameters (e.g., custom template)

        Returns:
            Markdown formatted string
        """
        # Load template
        template_name = kwargs.get("template", self.template_name)

        try:
            template = self.env.get_template(template_name)
        except Exception as e:
            logger.warning(f"Failed to load template {template_name}: {e}")
            # Fallback to default template
            template = self._get_default_template()

        # Render template
        content = template.render(**data)

        return content

    def _get_default_template(self) -> Template:
        """
        Get default Markdown template.

        Returns:
            Default Jinja2 template
        """
        default_template_str = """# {{title}}

{% if duration_estimate %}> **时长**: {{duration_estimate}}{% endif %}

## 📋 概述

{{summary}}

## 🔑 关键要点

{% for point in key_points %}
{% if point.importance == "high" %}### ⭐ {{point.point}}
{% elif point.importance == "medium" %}### {{point.point}}
{% else %}#### {{point.point}}
{% endif %}

{% endfor %}

## 📖 章节

{% for chapter in chapters %}
### {{chapter.title}}

{% if chapter.start_time %}> ⏱️ {{chapter.start_time}}{% if chapter.end_time %} - {{chapter.end_time}}{% endif %}{% endif %}

{{chapter.summary}}

{% endfor %}

{% for item in qa_items %}
{% if loop.first %}
## ❓ 常见问题

{% endif %}
**Q: {{item.question}}**

A: {{item.answer}}

{% endfor %}

{% if topics %}
## 🏷️ 主题标签

{% for topic in topics %}`{{topic}}` {% endfor %}

{% endif %}

---
*Generated by Learning Assistant*
"""

        return Template(default_template_str)
