"""
Cookie file management for authentication.

Handles importing, exporting, and validating cookies in Netscape format
(compatible with yt-dlp) and JSON format (browser extension export).
"""

import json
from pathlib import Path

from loguru import logger

from .models import CookieData


class CookieManager:
    """
    Cookie file manager.

    Manages cookies in Netscape format (yt-dlp compatible).
    """

    # Netscape cookie file header
    NETSCAPE_HEADER = """# Netscape HTTP Cookie File
# https://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Learning Assistant

"""

    def __init__(self, cookie_dir: str | Path):
        """
        Initialize CookieManager.

        Args:
            cookie_dir: Directory to store cookie files
        """
        self.cookie_dir = Path(cookie_dir)
        self.cookie_dir.mkdir(parents=True, exist_ok=True)

        logger.debug(f"CookieManager initialized with dir: {self.cookie_dir}")

    def export_cookies(
        self,
        cookies: list[CookieData],
        filename: str,
        include_header: bool = True,
    ) -> Path:
        """
        Export cookies to Netscape format file.

        Args:
            cookies: List of cookie data
            filename: Output filename (e.g., "bilibili_cookies.txt")
            include_header: Whether to include Netscape header

        Returns:
            Path to created cookie file
        """
        output_path = self.cookie_dir / filename

        with output_path.open("w", encoding="utf-8") as f:
            if include_header:
                f.write(self.NETSCAPE_HEADER)

            for cookie in cookies:
                line = cookie.to_netscape_line()
                f.write(line + "\n")

        logger.info(f"Exported {len(cookies)} cookies to {output_path}")
        return output_path

    def import_cookies(self, filename: str) -> list[CookieData]:
        """
        Import cookies from Netscape format file.

        Args:
            filename: Cookie filename (e.g., "bilibili_cookies.txt")

        Returns:
            List of cookie data

        Raises:
            FileNotFoundError: If cookie file doesn't exist
            ValueError: If cookie file format is invalid
        """
        cookie_file = self.cookie_dir / filename

        if not cookie_file.exists():
            raise FileNotFoundError(f"Cookie file not found: {cookie_file}")

        cookies = []

        with cookie_file.open("r", encoding="utf-8") as f:
            for line_num, line in enumerate(f, 1):
                line = line.strip()

                # Skip comments and empty lines
                if not line or line.startswith("#"):
                    continue

                # Parse cookie line
                parts = line.split("\t")

                if len(parts) != 7:
                    logger.warning(
                        f"Invalid cookie line {line_num}: expected 7 fields, got {len(parts)}"
                    )
                    continue

                domain, flag, path, secure, expires, name, value = parts

                cookie = CookieData(
                    domain=domain,
                    value=value,
                    path=path,
                    secure=(secure.upper() == "TRUE"),
                    expires=int(expires) if expires != "0" else None,
                    name=name,
                )

                cookies.append(cookie)

        logger.info(f"Imported {len(cookies)} cookies from {cookie_file}")
        return cookies

    def cookie_file_exists(self, filename: str) -> bool:
        """
        Check if cookie file exists.

        Args:
            filename: Cookie filename

        Returns:
            True if file exists, False otherwise
        """
        return (self.cookie_dir / filename).exists()

    def delete_cookie_file(self, filename: str) -> bool:
        """
        Delete cookie file.

        Args:
            filename: Cookie filename

        Returns:
            True if deleted, False if file didn't exist
        """
        cookie_file = self.cookie_dir / filename

        if cookie_file.exists():
            cookie_file.unlink()
            logger.info(f"Deleted cookie file: {cookie_file}")
            return True

        return False

    def validate_cookie_string(self, cookie_string: str) -> list[CookieData]:
        """
        Validate and parse cookie string from browser.

        Input format: "name1=value1; name2=value2; ..."

        Args:
            cookie_string: Raw cookie string from browser

        Returns:
            List of cookie data (without domain info - must be added separately)

        Raises:
            ValueError: If cookie string is invalid
        """
        if not cookie_string or not cookie_string.strip():
            raise ValueError("Cookie string is empty")

        cookies = []

        # Split by semicolon
        cookie_pairs = cookie_string.split(";")

        for pair in cookie_pairs:
            pair = pair.strip()

            if not pair:
                continue

            # Split by first equals sign
            if "=" not in pair:
                logger.warning(f"Invalid cookie pair: {pair}")
                continue

            name, value = pair.split("=", 1)
            name = name.strip()
            value = value.strip()

            if not name:
                logger.warning(f"Empty cookie name in pair: {pair}")
                continue

            # Create cookie data (domain must be set by caller)
            cookie = CookieData(
                name=name,
                value=value,
                domain="",  # Will be set by caller
                path="/",
                secure=False,
                expires=None,
            )

            cookies.append(cookie)

        if not cookies:
            raise ValueError("No valid cookies found in string")

        logger.info(f"Validated {len(cookies)} cookies from string")
        return cookies

    def validate_json_cookies(self, json_string: str) -> list[CookieData]:
        """
        Validate and parse JSON cookie export from browser extension.

        Input format: JSON array of cookie objects (from "Get cookies.txt" extension)
        Example: [{"name": "SESSDATA", "value": "xxx", "domain": ".bilibili.com", ...}]

        Args:
            json_string: JSON string of cookie array

        Returns:
            List of cookie data

        Raises:
            ValueError: If JSON is invalid or no valid cookies found
        """
        if not json_string or not json_string.strip():
            raise ValueError("JSON cookie string is empty")

        try:
            cookie_list = json.loads(json_string)
        except json.JSONDecodeError as e:
            raise ValueError(f"Invalid JSON: {e}")

        if not isinstance(cookie_list, list):
            raise ValueError("JSON must be an array of cookie objects")

        cookies = []

        for cookie_obj in cookie_list:
            if not isinstance(cookie_obj, dict):
                logger.warning(f"Invalid cookie object: {cookie_obj}")
                continue

            name = cookie_obj.get("name")
            value = cookie_obj.get("value")

            if not name or not value:
                logger.warning(f"Cookie missing name or value: {cookie_obj}")
                continue

            # Extract domain (may be ".bilibili.com" or "bilibili.com")
            domain = cookie_obj.get("domain", "")

            # Extract other fields
            path = cookie_obj.get("path", "/")
            secure = cookie_obj.get("secure", False)

            # Handle expiration
            expires = None
            if cookie_obj.get("expirationDate"):
                # expirationDate is Unix timestamp (can be float)
                expires = int(cookie_obj["expirationDate"])

            cookie = CookieData(
                name=name,
                value=value,
                domain=domain,
                path=path,
                secure=secure,
                expires=expires,
            )

            cookies.append(cookie)

        if not cookies:
            raise ValueError("No valid cookies found in JSON")

        logger.info(f"Validated {len(cookies)} cookies from JSON")
        return cookies

    def parse_cookies_auto(self, input_string: str) -> list[CookieData]:
        """
        Auto-detect and parse cookies from either JSON or string format.

        Args:
            input_string: Cookie input (JSON array or "name=value; ..." string)

        Returns:
            List of cookie data
        """
        input_string = input_string.strip()

        # Try JSON first (starts with '[')
        if input_string.startswith("["):
            try:
                return self.validate_json_cookies(input_string)
            except ValueError as e:
                logger.warning(f"JSON parse failed, trying string format: {e}")

        # Fall back to string format
        return self.validate_cookie_string(input_string)

    def get_cookie_file_path(self, filename: str) -> Path:
        """
        Get absolute path to cookie file.

        Args:
            filename: Cookie filename

        Returns:
            Absolute path to cookie file
        """
        return self.cookie_dir / filename
